base_url = "https://www.maxsarratt.com"
build_search_index = false
compile_sass = false
default_language = "zh"
description = "ä¸»è¦å…³æ³¨æ³¨æ„åŠ›ç®¡ç†ï¼Œæ·±åº¦å·¥ä½œï¼Œè‹±æ–‡å­¦ä¹ ï¼Œåç›´è§‰, æŠ€æœ¯ï¼Œè¯»ä¹¦ï¼Œæ‘˜æŠ„ï¼Œæ‚è°ˆï¼Œæ–‡ç« è¯„è®ºï¼Œå·¥å…·åˆ†äº«ï¼Œå·¥ä½œæµï¼Œçµæ„Ÿï¼Œç­‰æ–¹å‘"
generate_feed = true
generate_rss = true
taxonomies = [
  {name = "tags", feed = true, paginate_by = 20, lang = "zh"},
  {name = "categories", feed = true, paginate_by = 20, lang = "zh"},
]
title = "Max's Blog"

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true
# highlight_theme = "Tomorrow"
# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true
smart_punctuation = true
[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = true
# Whether to include the rendered content of the page/section in the index
include_content = false

[extra]
author = "Max"
email = "maxsarratt@gmail.com"
theme_color = "#EA4C89"

### indieweb note
bio = "Web developer, I like reading and explore the internet, so I have collected queit a few notes in my blog."
### THIRD PARTY
# google_analytics = "UA-012345-67"
# disqus = "disqus-user"

### SOCIAL MEDIA
edit_url_prefix = "https://github.com/theowenyoung/blog/tree/main/content/"
github_user = "maxsarratt"
image = "https://www.owenyoung.com/logo.png"
"label_action_in-reply-to" = "replied"
"label_action_mention-of" = "mentioned"
"label_action_reply-to" = "replied"
"label_action_rsvp" = "answered"
twitter_user = ""
webmention_path = "webmentions"
### I18N WORDS

[slugify]
anchors = "on"
paths = "on"
taxonomies = "on"

[languages.zh]
description = "ä¸»è¦å…³æ³¨æŠ€æœ¯ï¼Œè¯»ä¹¦ï¼Œæ‘˜æŠ„ï¼Œæ‚è°ˆï¼Œæ–‡ç« è¯„è®ºï¼Œå·¥å…·åˆ†äº«ï¼Œå·¥ä½œæµï¼Œçµæ„Ÿï¼Œè‹±æ–‡å­¦ä¹ ï¼Œæ³¨æ„åŠ›ç®¡ç†ï¼Œæ·±åº¦å·¥ä½œç­‰æ–¹å‘"
title = "Max's Blog"

[languages.zh.translations]

keywords = "æ³¨æ„åŠ›, è¯»ä¹¦, å·¥å…·åˆ†äº«, çº¯æ–‡æœ¬, è‹±è¯­å­¦ä¹ "
label_all_posts = "[ç‚¹å‡»æŸ¥çœ‹æ‰€æœ‰æ–‡ç« ğŸ”¥ğŸ”¥](/blog/)"
label_all_thoughts = "[ç‚¹å‡»æŸ¥çœ‹æ‰€æœ‰çŸ­æƒ³æ³•ğŸ”¥ğŸ”¥](/thoughts/)"
label_archive = "Archive"
label_back_to_start = "Get Started"
label_book_author = "Book Author"
"label_bookmark-of" = "Bookmarks"
label_books = "All books reviews"
label_categories = "Categories"
label_category = "Category"
label_created = "Published"
label_edit = "Edit this page"
"label_follow-of" = "Follows"
label_home = "Home"
"label_in-reply-to" = "Replies"
label_latest_notes_title = "[Recently Updated](/categories/notes/)ï¼š"
"label_like-of" = "Likes"
label_links = "Links"
"label_mention-of" = "Mentions"
label_new_posts_list_title = "[Latest](/en/blog/) Articles:"
label_notes_title = "All Notes [(sort by update time)](/en/categories/notes/):"
label_published_on = "on"
label_rating = "Rating"
label_read_more = "Continue to Read"
label_reading = "Reading Time"
"label_repost-of" = "Reposts"
label_response = "Response"
label_response_description = "The following responses are collected by the [webmention.io](https://webmention.io/) service."
label_rss = "Subscribe RSS"
"label_rsvp" = "RSVP"
label_table_contents = "On this page"
label_tag = "Tag"
label_tags = "Tags"
label_target_language = "English Blog"
label_taxonomy = "Taxonomy"
label_thoughts_title = "Latest [Short Thoughts](/en/thoughts/)ï¼š"
label_updated = "Updated"

[languages.en]
build_search_index = true
description = "Mainly focus on technology, reading, excerpts, miscellaneous, article review, tool sharing, workflow, inspiration, English learning, attention management, deep work and other directions"
taxonomies = [
  {name = "tags", feed = true, paginate_by = 20, lang = "en"},
  {name = "categories", feed = true, paginate_by = 20, lang = "en"},
]
title = "Max's Blog"
[languages.en.translations]
keywords = "Focus, Reading, Tool sharing, Plain text, English learning"
label_all_posts = "[View all posts](/en/blog/)"
label_all_thoughts = "[View all thoughtsğŸ”¥ğŸ”¥](/en/thoughts/)"
label_archive = "Archive"
label_back_to_start = "Get Started"
label_book_author = "Book Author"
"label_bookmark-of" = "Bookmarks"
label_books = "All books reviews"
label_categories = "Categories"
label_category = "Category"
label_created = "Published"
label_edit = "Edit this page"
"label_follow-of" = "Follows"
label_home = "Home"
"label_in-reply-to" = "Replies"
label_latest_notes_title = "[Recently Updated](/categories/notes/)ï¼š"
"label_like-of" = "Likes"
label_links = "Links"
"label_mention-of" = "Mentions"
label_new_posts_list_title = "[Latest](/en/blog/) Articles:"
label_notes_title = "All Notes [(sort by update time)](/en/categories/notes/):"
label_published_on = "on"
label_rating = "Rating"
label_read_more = "Continue to Read"
label_reading = "Reading Time"
"label_repost-of" = "Reposts"
label_response = "Response"
label_response_description = "The following responses are collected by the [webmention.io](https://webmention.io/) service."
label_rss = "Subscribe RSS"
"label_rsvp" = "RSVP"
label_table_contents = "On this page"
label_tag = "Tag"
label_tags = "Tags"
label_target_language = "ä¸­æ–‡åšå®¢"
label_taxonomy = "Taxonomy"
label_thoughts_title = "Latest [Short Thoughts](/en/thoughts/)ï¼š"
label_updated = "Updated"
